version: '3.5'
services:
  mysql:
    image: mysql:8.0
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=cvr
      - MYSQL_PASSWORD=cvr
      - MYSQL_DATABASE=cvr
volumes:
  data:
networks:
  mysql:
    name: mysql
